title: V Pay
baseURL: /
params:
  footer:
    content: '&copy; V Pay. All rights reserved.'
    has_nav: true
    has_social: true
    has_subscribe: true
    links:
      - new_window: true
        text: Powered by V Pay Team
        url: 'https://www.vpay.com'
    logo_img: images/logo_alt.png
    nav_title: Company
    social_title: Community
    subscribe_content: Stay up to date with our latest developments.
    subscribe_title: Subscribe
    tagline: >-
      A secure and real-time platform for merchants to deal with crypto-payments
      and become enablers of a financially inclusive future that is fast, secure
      and comes at a minimal cost.
  header:
    has_nav: true
    logo_img: images/logo.png
    title: V Pay
    menu:
      actions:
        - label: Wait List
          url: /sign-up-for-wait-list
  palette: blue
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
