title: VPay
baseURL: /
params:
  footer:
    content: '&copy; VPay. All rights reserved.'
    has_nav: true
    has_social: true
    has_subscribe: true
    links:
      - new_window: true
        text: Powered by VPay Team
        url: 'https://www.vpay.com'
    logo_img: images/logo_alt.png
    nav_title: Company
    social_title: Community
    subscribe_content: Stay up to date with our latest developments.
    subscribe_title: Subscribe
    tagline: Fiat-Stable Coins For Merchants
  header:
    has_nav: true
    logo_img: images/logo.png
    title: VPay
    menu:
      actions:
        - label: Wait List
          url: /signup
  palette: blue
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
